# Generated by Django 2.1.8 on 2019-04-26 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_user',
            field=models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
